### ISSUE TITLE
When logging in with aws-adfs and Duo MFA

### ISSUE THREAD

**Issue by anthoneous** [venth/aws-adfs#34] opened 2017-05-02 18:57 UTC
Hello,

When I login with AWS-ADFS and Duo MFA and the sts session expires it Duo prompts me again. Is there a way to use the ADFS session time and skip the Duo prompt until the ADFS session token expires?

For example, if I logged in and my ADFS session is set for four hours then I shouldn't be prompted to authenticate with Duo again for another four hours even if the AWS session expired.

This change can allow a feature like auto-renew aws cli session (just like the aws cli already does with access keys) for some tasks that could take longer than an hour.

**Comment by venth** [comment] 2017-05-03 07:30
It would be feasible with usage of a cron job. I would like to avaid adding such an automation. I'll look into sts documentation to see what are the options to extend session time.

**Comment by anthony-estevez-zefr** [comment] 2017-05-03 21:23
Thanks for the follow up. I think if are can imitate the way ADFS handles duo authentication that would be a great start. ADFS authenticates with Duo once and won't prompt for authentication with Duo again until the session in ADFS is done.

I did find the following attempts regarding the sts session renewals:

https://github.com/boto/boto3/issues/1019
https://github.com/msabramo/aws-cli-get-token-command
https://github.com/aws/aws-sdk-ruby/issues/520

**Comment by venth** [comment] 2017-05-04 09:09
Smart solution. I'll think about something similar.

**Comment by venth** [comment] 2017-06-15 09:11
I thought about the decoration command that in case of expired session would execute adfs-aws to re-authenticate and then proceed with original aws cli command.
Introduction of the decoration command that would be named the same as original one seems to be a little complicated.

I would like to propose the introduction of `awsa` command that would delegate the execution to aws command; in case of session expiration failure it would re-authenticate via aws-adfs and re-execute the aws command.

@anthony-estevez-zefr what do you think about the afore mentioned behavior?

**Comment by anthony-estevez-zefr** [comment] 2017-06-16 20:43
I think that should work.

**Comment by anthoneous** [comment] 2017-08-25 18:51
@venth https://gist.github.com/kapilt/ac8e222081f63ba64e93 appears to partially address the issue. What do you think?

**Comment by venth** [comment] 2017-08-25 19:30
Looks awesome, I'll try it.

**Comment by venth** [comment] 2017-09-17 14:48
I found the solution. As I afore mentioned, I'll introduce the command: `awsr`

In order to use re-authentication mechanism just use `awsr` instead of the regular `aws` command. The example command: `awsr s3 ls`

The change is in the way.

**Comment by venth** [comment] 2017-09-17 19:48
`awsr` command line tool delivered with version: 0.3.13. @anthoneous please verify, if it works as intended.

**Comment by anthoneous** [comment] 2017-09-18 20:19
Currently, not working in my first few tests but appears to be on the right track. Here's the error I received:

01:07 PM: > aws s3 ls
'--adfs-host' parameter must be supplied
Traceback (most recent call last):
  File "/Users/anthoneous/.pyenv/versions/2.7.13/bin/awsr", line 11, in <module>
    load_entry_point('aws-adfs==0.3.13', 'console_scripts', 'awsr')()
  File "/Users/anthoneous/.pyenv/versions/2.7.13/lib/python2.7/site-packages/aws_adfs/aws_refreshable.py", line 30, in decorate
    _re_authenticate(driver)
  File "/Users/anthoneous/.pyenv/versions/2.7.13/lib/python2.7/site-packages/aws_adfs/aws_refreshable.py", line 38, in _re_authenticate
    subprocess.check_call('aws-adfs login --profile {}'.format(profile), shell=True)
  File "/Users/anthoneous/.pyenv/versions/2.7.13/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'aws-adfs login --profile None' returned non-zero exit status 255

**Comment by venth** [comment] 2017-09-18 20:47
Hmm, I forgot that `awsr` can be used without prior usage of `aws-adfs` command. If adfs host will be missing then the command simply will ask for it.

**Comment by anthoneous** [comment] 2017-09-18 22:49
Forgot to add, I was already logged in with ```aws-adfs``` at 12:07pm and attempted to run the ```awsr``` command at 1:07pm.

**Comment by venth** [comment] 2017-09-19 06:51
Version 0.3.14 ready is ready :)

**Comment by anthoneous** [comment] 2017-09-20 18:45
Appears to be working correctly.

**Comment by venth** [comment] 2017-09-20 18:48
Could I ask to close this issue?

**Closed** 2017-09-20 19:53 UTC
Labels: enhancement
